### ISSUE TITLE
Trabajo infografía 

### ISSUE THREAD

**Issue by Johnc-byte** [SistemasTecTlaxiaco/infografia-Johnc-byte#1]
[
[24620197_jonathan_cruz_cuevas_.pdf](https://github.com/user-attachments/files/16841653/24620197_jonathan_cruz_cuevas_.pdf)

**Comment by Nelson295281** [comment]
Redacción y ortografía: 13/14
Exposición de ideas centrales: 16/16
Organización de ideas centrales: 14/14
Uso de imágenes y colores: 14/14
Presentación visual: 14/14
Presentación: 14/14
Referencias: 14/14
Calificación final : 19.8/20
